// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/execs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a list of all execs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execs"
                ],
                "summary": "Get all executives",
                "operationId": "getExecs",
                "responses": {
                    "200": {
                        "description": "List of execs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Exec"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new executive user with first name, last name, role, and email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execs"
                ],
                "summary": "Create a new executive (exec)",
                "operationId": "createExec",
                "parameters": [
                    {
                        "description": "Exec payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateExecPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the created exec object",
                        "schema": {
                            "$ref": "#/definitions/store.Exec"
                        }
                    },
                    "400": {
                        "description": "Bad request, validation failed",
                        "schema": {}
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {}
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {}
                    },
                    "409": {
                        "description": "Conflict, exec already exists",
                        "schema": {}
                    },
                    "429": {
                        "description": "Rate limit exceeded",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            }
        },
        "/execs/{execID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a single exec by ID (must be set in context via middleware)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execs"
                ],
                "summary": "Get a single executive",
                "operationId": "getExec",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exec ID",
                        "name": "execID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exec object",
                        "schema": {
                            "$ref": "#/definitions/store.Exec"
                        }
                    },
                    "404": {
                        "description": "Exec not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deletes an exec by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execs"
                ],
                "summary": "Delete an executive",
                "operationId": "deleteExec",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exec ID",
                        "name": "execID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Exec not found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Updates an exec. Only non-nil fields in the payload are updated. Versioning ensures concurrency safety.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "execs"
                ],
                "summary": "Update an executive",
                "operationId": "updateExec",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exec ID",
                        "name": "execID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Exec fields to update",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateExecPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated exec object",
                        "schema": {
                            "$ref": "#/definitions/store.Exec"
                        }
                    },
                    "400": {
                        "description": "Bad request / validation failed",
                        "schema": {}
                    },
                    "404": {
                        "description": "Exec not found",
                        "schema": {}
                    },
                    "409": {
                        "description": "Conflict / concurrent update",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            }
        },
        "/teachers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Get all teachers",
                "operationId": "getTeachers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Teacher"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new teacher with first name, last name, email, subject, and optional phone.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Create a new teacher",
                "operationId": "createTeacher",
                "parameters": [
                    {
                        "description": "Teacher payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateTeacherPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the created teacher",
                        "schema": {
                            "$ref": "#/definitions/store.Teacher"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {}
                    },
                    "409": {
                        "description": "Conflict, teacher already exists",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {}
                    }
                }
            }
        },
        "/teachers/{teacherID}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Get a teacher by ID",
                "operationId": "getTeacher",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Teacher ID",
                        "name": "teacherID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Teacher"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Delete a teacher",
                "operationId": "deleteTeacher",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Teacher ID",
                        "name": "teacherID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teachers"
                ],
                "summary": "Update a teacher",
                "operationId": "updateTeacher",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Teacher ID",
                        "name": "teacherID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Teacher update payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateTeacherPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Teacher"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {}
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "main.CreateExecPayload": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "role": {
                    "enum": [
                        "admin",
                        "manager"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/store.Role"
                        }
                    ]
                }
            }
        },
        "main.CreateTeacherPayload": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "hire_date",
                "last_name",
                "phone_number",
                "subject"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "hire_date": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "phone_number": {
                    "type": "string"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 128
                }
            }
        },
        "main.UpdateExecPayload": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "role": {
                    "enum": [
                        "admin",
                        "manager"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/store.Role"
                        }
                    ]
                }
            }
        },
        "main.UpdateTeacherPayload": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "hire_date": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 72
                },
                "phone_number": {
                    "type": "string"
                },
                "subject": {
                    "type": "string",
                    "maxLength": 128
                }
            }
        },
        "store.Exec": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/store.Role"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "store.Role": {
            "type": "string",
            "enum": [
                "admin",
                "manager"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleManager"
            ]
        },
        "store.Teacher": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "hire_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "ClassNama",
	Description:      "API for ClassNama, a school management platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
